CREATE TABLE main (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date_time DATETIME NOT NULL,
  user_id INTEGER NOT NULL,
  server_id INTEGER NOT NULL,
  ip_id INTEGER NOT NULL,
  cs BIGINT NOT NULL,
  sc BIGINT NOT NULL,
  status_id INTEGER,
  connection_type_id INTEGER NOT NULL,
  uri TEXT,
  r_server_id INTEGER NOT NULL,
  rule_id INTEGER,
  agent_id INTEGER,
  FOREIGN KEY (user_id) REFERENCES user(id),
  FOREIGN KEY (server_id) REFERENCES server(id),
  FOREIGN KEY (ip_id) REFERENCES ip(id),
  FOREIGN KEY (status_id) REFERENCES status(id),
  FOREIGN KEY (connection_type_id) REFERENCES connection_type(id),
  FOREIGN KEY (r_server_id) REFERENCES r_server(id),
  FOREIGN KEY (rule_id) REFERENCES rule(id),
  FOREIGN KEY (agent_id) REFERENCES agent(id)
);

CREATE INDEX date_time_index ON main (date_time);

CREATE TABLE connection_type (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value TEXT UNIQUE NOT NULL
);

CREATE TABLE server (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value TEXT UNIQUE NOT NULL
);

CREATE TABLE status (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value TEXT UNIQUE NOT NULL
);

CREATE TABLE rule (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value TEXT UNIQUE NOT NULL
);

CREATE TABLE agent (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value TEXT UNIQUE NOT NULL
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value TEXT UNIQUE NOT NULL
);
CREATE INDEX user_index ON user (value);

CREATE TABLE r_server (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value TEXT UNIQUE NOT NULL
);
CREATE INDEX r_server_index ON r_server (value);

CREATE TABLE ip (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value TEXT UNIQUE NOT NULL
);
CREATE INDEX ip_index ON ip (value);
