CREATE TABLE main (
id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
date__time datetime NOT NULL,
user SMALLINT UNSIGNED NOT NULL,
server TINYINT UNSIGNED NOT NULL,
ip MEDIUMINT UNSIGNED NOT NULL,
cs BIGINT UNSIGNED NOT NULL,
sc BIGINT UNSIGNED NOT NULL,
status TINYINT UNSIGNED,
connection_type TINYINT UNSIGNED NOT NULL,
uri VARCHAR(24000),
r_server TINYINT UNSIGNED NOT NULL,
rule SMALLINT UNSIGNED,
agent SMALLINT UNSIGNED);

CREATE INDEX date_time_index ON main (date__time);


CREATE TABLE connection_type (
  id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  value VARCHAR(64) UNIQUE NOT NULL
);


CREATE TABLE server (
  id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  value VARCHAR(64) UNIQUE NOT NULL
);


CREATE TABLE status (
  id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  value VARCHAR(16) UNIQUE NOT NULL
);


CREATE TABLE rule (
  id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  value VARCHAR(128) UNIQUE NOT NULL
);


CREATE TABLE agent (
  id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  value VARCHAR(256) UNIQUE NOT NULL
);


CREATE TABLE user (
  id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  value VARCHAR(64) UNIQUE NOT NULL
);
CREATE INDEX user_index ON user (value);

CREATE TABLE r_server (
  id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  value VARCHAR(64) UNIQUE NOT NULL
);
CREATE INDEX r_server_index on r_server (value);


CREATE TABLE ip (
  id MEDIUMINT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
  value VARCHAR(16) UNIQUE NOT NULL
);
CREATE INDEX ip_index ON ip (value);
